// Generated by LeetCodeContestHelper at 4/30/2024, 3:33:27 AM
// 3120. Count the Number of Special Characters I
// https://leetcode.com/contest/weekly-contest-394/problems/count-the-number-of-special-characters-i/

#define _USE_MATH_DEFINES
#include <algorithm>
#include <array>
#include <bitset>
#include <climits>
#include <cmath>
#include <deque>
#include <forward_list>
#include <functional>
#include <iomanip>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <numeric>
#include <queue>
#include <regex>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <tuple>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <valarray>
#include <vector>

using namespace std;

class Solution {
   public:
    int numberOfSpecialChars(string word) {
        int ans = 0;
        for (int i = 0; i < 26; i++) {
            if (word.find(char(i + 'a')) != string::npos &&
                word.find(char(i + 'A')) != string::npos) {
                ans++;
            }
        }
        return ans;
    }
};

// int Solution::numberOfSpecialChars(string word)

int main() {
    cout << "*** 3120. Count the Number of Special Characters I ***" << endl
         << endl;

    Solution s0;

    {
        cout << "Test 1: ";

        string word = "aaAbcBC";
        int ans0 = s0.numberOfSpecialChars(word);
        int exp0 = 3;

        if (ans0 == exp0) {
            cout << "Yes" << endl;
        } else {
            cout << "No" << endl;
            cout << "  Answer: " << ans0 << endl;
            cout << "  Expect: " << exp0 << endl;
        }
    }

    {
        cout << "Test 2: ";

        string word = "abc";
        int ans1 = s0.numberOfSpecialChars(word);
        int exp1 = 0;

        if (ans1 == exp1) {
            cout << "Yes" << endl;
        } else {
            cout << "No" << endl;
            cout << "  Answer: " << ans1 << endl;
            cout << "  Expect: " << exp1 << endl;
        }
    }

    {
        cout << "Test 3: ";

        string word = "abBCab";
        int ans2 = s0.numberOfSpecialChars(word);
        int exp2 = 1;

        if (ans2 == exp2) {
            cout << "Yes" << endl;
        } else {
            cout << "No" << endl;
            cout << "  Answer: " << ans2 << endl;
            cout << "  Expect: " << exp2 << endl;
        }
    }

    return 0;
}
