// Generated by LeetCodeContestHelper at 4/30/2024, 3:33:36 AM
// 3121. Count the Number of Special Characters II
// https://leetcode.com/contest/weekly-contest-394/problems/count-the-number-of-special-characters-ii/

#define _USE_MATH_DEFINES
#include <algorithm>
#include <array>
#include <bitset>
#include <climits>
#include <cmath>
#include <deque>
#include <forward_list>
#include <functional>
#include <iomanip>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <numeric>
#include <queue>
#include <regex>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <tuple>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <valarray>
#include <vector>

using namespace std;

class Solution {
   public:
    int numberOfSpecialChars(string word) {
        map<char, int> mp;
        int ans = 0;
        for (int i = 0; i < (int)word.size(); i++) {
            char c = word[i];
            if (c >= 'A' && c <= 'Z') {
                if (!mp.count(c)) {
                    mp[c] = i;
                }
            } else {
                mp[c] = i;
            }
        }
        for (int i = 0; i < 26; i++) {
            if (mp.count(char(i + 'a')) && mp.count(char(i + 'A')) &&
                mp[char(i + 'a')] < mp[char(i + 'A')]) {
                ans++;
            }
        }
        return ans;
    }
};

// int Solution::numberOfSpecialChars(string word)

int main() {
    cout << "*** 3121. Count the Number of Special Characters II ***" << endl
         << endl;

    Solution s0;

    {
        cout << "Test 1: ";

        string word = "aaAbcBC";
        int ans0 = s0.numberOfSpecialChars(word);
        int exp0 = 3;

        if (ans0 == exp0) {
            cout << "Yes" << endl;
        } else {
            cout << "No" << endl;
            cout << "  Answer: " << ans0 << endl;
            cout << "  Expect: " << exp0 << endl;
        }
    }

    {
        cout << "Test 2: ";

        string word = "abc";
        int ans1 = s0.numberOfSpecialChars(word);
        int exp1 = 0;

        if (ans1 == exp1) {
            cout << "Yes" << endl;
        } else {
            cout << "No" << endl;
            cout << "  Answer: " << ans1 << endl;
            cout << "  Expect: " << exp1 << endl;
        }
    }

    {
        cout << "Test 3: ";

        string word = "AbBCab";
        int ans2 = s0.numberOfSpecialChars(word);
        int exp2 = 0;

        if (ans2 == exp2) {
            cout << "Yes" << endl;
        } else {
            cout << "No" << endl;
            cout << "  Answer: " << ans2 << endl;
            cout << "  Expect: " << exp2 << endl;
        }
    }

    return 0;
}
