// Generated by LeetCodeContestHelper at 4/30/2024, 3:29:43 AM
// 3091. Apply Operations to Make Sum of Array Greater Than or Equal to k
// https://leetcode.com/contest/weekly-contest-390/problems/apply-operations-to-make-sum-of-array-greater-than-or-equal-to-k/

#define _USE_MATH_DEFINES
#include <algorithm>
#include <array>
#include <bitset>
#include <climits>
#include <cmath>
#include <deque>
#include <forward_list>
#include <functional>
#include <iomanip>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <numeric>
#include <queue>
#include <regex>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <tuple>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <valarray>
#include <vector>

using namespace std;

class Solution {
 public:
  int minOperations(int k) {
    if (k == 0 || k == 1)
      return 0;
    int ans = INT_MAX;
    for (int i = 2; i <= k; i++) {
      int t = k / i;
      if (k % i) {
        t++;
      }
      t--;
      ans = min(ans, i - 1 + t);
    }
    return ans;
  }
};

// int Solution::minOperations(int k)

int main() {
  cout << "*** 3091. Apply Operations to Make Sum of Array Greater Than or "
          "Equal to k ***"
       << endl
       << endl;

  Solution s0;

  {
    cout << "Test 1: ";

    int k = 11;
    int ans0 = s0.minOperations(k);
    int exp0 = 5;

    if (ans0 == exp0) {
      cout << "Yes" << endl;
    } else {
      cout << "No" << endl;
      cout << "  Answer: " << ans0 << endl;
      cout << "  Expect: " << exp0 << endl;
    }
  }

  {
    cout << "Test 2: ";

    int k = 1;
    int ans1 = s0.minOperations(k);
    int exp1 = 0;

    if (ans1 == exp1) {
      cout << "Yes" << endl;
    } else {
      cout << "No" << endl;
      cout << "  Answer: " << ans1 << endl;
      cout << "  Expect: " << exp1 << endl;
    }
  }

  return 0;
}
