// Generated by LeetCodeContestHelper at 4/30/2024, 3:26:24 AM
// 3083. Existence of a Substring in a String and Its Reverse
// https://leetcode.com/contest/weekly-contest-389/problems/existence-of-a-substring-in-a-string-and-its-reverse/

#define _USE_MATH_DEFINES
#include <climits>
#include <cmath>

#include <array>
#include <deque>
#include <forward_list>
#include <list>
#include <map>
#include <queue>
#include <set>
#include <stack>
#include <unordered_map>
#include <unordered_set>
#include <vector>

#include <iomanip>
#include <iostream>
#include <sstream>

#include <algorithm>
#include <bitset>
#include <functional>
#include <iterator>
#include <limits>
#include <numeric>
#include <regex>
#include <string>
#include <tuple>
#include <utility>
#include <valarray>

using namespace std;

class Solution {
public:
    bool isSubstringPresent(string s) {
        string t = s;
        reverse(t.begin(), t.end());
        for (int i = 0; i < (int) s.size() - 1; i++) {
            if (t.find(s.substr(i, 2)) != string::npos) {
                return true;
            }
        }
        return false;
    }
};

// bool Solution::isSubstringPresent(string s)

int main() {
    cout << "*** 3083. Existence of a Substring in a String and Its Reverse ***" << endl << endl;

    Solution s0;

    {
        cout << "Test 1: ";

        string s = "leetcode";
        bool ans0 = s0.isSubstringPresent(s);
        bool exp0 = true;

        if (ans0 == exp0) {
            cout << "Yes" << endl;
        }
        else {
            cout << "No" << endl;
            cout << "  Answer: " << ans0 << endl;
            cout << "  Expect: " << exp0 << endl;
        }
    }

    {
        cout << "Test 2: ";

        string s = "abcba";
        bool ans1 = s0.isSubstringPresent(s);
        bool exp1 = true;

        if (ans1 == exp1) {
            cout << "Yes" << endl;
        }
        else {
            cout << "No" << endl;
            cout << "  Answer: " << ans1 << endl;
            cout << "  Expect: " << exp1 << endl;
        }
    }

    {
        cout << "Test 3: ";

        string s = "abcd";
        bool ans2 = s0.isSubstringPresent(s);
        bool exp2 = false;

        if (ans2 == exp2) {
            cout << "Yes" << endl;
        }
        else {
            cout << "No" << endl;
            cout << "  Answer: " << ans2 << endl;
            cout << "  Expect: " << exp2 << endl;
        }
    }

    return 0;
}
