// Generated by LeetCodeContestHelper at 4/30/2024, 3:26:51 AM
// 3084. Count Substrings Starting and Ending with Given Character
// https://leetcode.com/contest/weekly-contest-389/problems/count-substrings-starting-and-ending-with-given-character/

#define _USE_MATH_DEFINES
#include <algorithm>
#include <array>
#include <bitset>
#include <climits>
#include <cmath>
#include <deque>
#include <forward_list>
#include <functional>
#include <iomanip>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <numeric>
#include <queue>
#include <regex>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <tuple>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <valarray>
#include <vector>

using namespace std;

class Solution {
 public:
  long long countSubstrings(string s, char c) {
    long long t = (long long)count(s.begin(), s.end(), c);
    return t * (t + 1) / 2;
  }
};

// long long Solution::countSubstrings(string s, char c)

int main() {
  cout << "*** 3084. Count Substrings Starting and Ending with Given Character "
          "***"
       << endl
       << endl;

  Solution s0;

  {
    cout << "Test 1: ";

    string s = "abada";
    char c = 'a';
    long long ans0 = s0.countSubstrings(s, c);
    long long exp0 = 6;

    if (ans0 == exp0) {
      cout << "Yes" << endl;
    } else {
      cout << "No" << endl;
      cout << "  Answer: " << ans0 << endl;
      cout << "  Expect: " << exp0 << endl;
    }
  }

  {
    cout << "Test 2: ";

    string s = "zzz";
    char c = 'z';
    long long ans1 = s0.countSubstrings(s, c);
    long long exp1 = 6;

    if (ans1 == exp1) {
      cout << "Yes" << endl;
    } else {
      cout << "No" << endl;
      cout << "  Answer: " << ans1 << endl;
      cout << "  Expect: " << exp1 << endl;
    }
  }

  return 0;
}
