// Generated by LeetCodeContestHelper at 4/30/2024, 3:30:44 AM
// 3099. Harshad Number
// https://leetcode.com/contest/weekly-contest-391/problems/harshad-number/

#define _USE_MATH_DEFINES
#include <algorithm>
#include <array>
#include <bitset>
#include <climits>
#include <cmath>
#include <deque>
#include <forward_list>
#include <functional>
#include <iomanip>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <numeric>
#include <queue>
#include <regex>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <tuple>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <valarray>
#include <vector>

using namespace std;

class Solution {
 public:
  int sumOfTheDigitsOfHarshadNumber(int x) {
    string s = to_string(x);
    int t = 0;
    for (auto& e : s) {
      t += e - '0';
    }
    if (x % t)
      return -1;
    return t;
  }
};

// int Solution::sumOfTheDigitsOfHarshadNumber(int x)

int main() {
  cout << "*** 3099. Harshad Number ***" << endl << endl;

  Solution s0;

  {
    cout << "Test 1: ";

    int x = 18;
    int ans0 = s0.sumOfTheDigitsOfHarshadNumber(x);
    int exp0 = 9;

    if (ans0 == exp0) {
      cout << "Yes" << endl;
    } else {
      cout << "No" << endl;
      cout << "  Answer: " << ans0 << endl;
      cout << "  Expect: " << exp0 << endl;
    }
  }

  {
    cout << "Test 2: ";

    int x = 23;
    int ans1 = s0.sumOfTheDigitsOfHarshadNumber(x);
    int exp1 = -1;

    if (ans1 == exp1) {
      cout << "Yes" << endl;
    } else {
      cout << "No" << endl;
      cout << "  Answer: " << ans1 << endl;
      cout << "  Expect: " << exp1 << endl;
    }
  }

  return 0;
}
