// Generated by LeetCodeContestHelper at 4/30/2024, 3:30:47 AM
// 3100. Water Bottles II
// https://leetcode.com/contest/weekly-contest-391/problems/water-bottles-ii/

#define _USE_MATH_DEFINES
#include <algorithm>
#include <array>
#include <bitset>
#include <climits>
#include <cmath>
#include <deque>
#include <forward_list>
#include <functional>
#include <iomanip>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <numeric>
#include <queue>
#include <regex>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <tuple>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <valarray>
#include <vector>

using namespace std;

class Solution {
 public:
  int maxBottlesDrunk(int numBottles, int numExchange) {
    int ans = numBottles;
    while (numBottles >= numExchange) {
      ans++;
      numBottles -= numExchange;
      numExchange++;
      numBottles++;
    }
    return ans;
  }
};

// int Solution::maxBottlesDrunk(int numBottles, int numExchange)

int main() {
  cout << "*** 3100. Water Bottles II ***" << endl << endl;

  Solution s0;

  {
    cout << "Test 1: ";

    int numBottles = 13;
    int numExchange = 6;
    int ans0 = s0.maxBottlesDrunk(numBottles, numExchange);
    int exp0 = 15;

    if (ans0 == exp0) {
      cout << "Yes" << endl;
    } else {
      cout << "No" << endl;
      cout << "  Answer: " << ans0 << endl;
      cout << "  Expect: " << exp0 << endl;
    }
  }

  {
    cout << "Test 2: ";

    int numBottles = 10;
    int numExchange = 3;
    int ans1 = s0.maxBottlesDrunk(numBottles, numExchange);
    int exp1 = 13;

    if (ans1 == exp1) {
      cout << "Yes" << endl;
    } else {
      cout << "No" << endl;
      cout << "  Answer: " << ans1 << endl;
      cout << "  Expect: " << exp1 << endl;
    }
  }

  return 0;
}
