// Generated by LeetCodeContestHelper at 5/18/2025, 9:30:33 AM
// 100668. Smallest Index With Digit Sum Equal to Index
// https://leetcode.com/contest/weekly-contest-450/problems/smallest-index-with-digit-sum-equal-to-index/

#define _USE_MATH_DEFINES
#include <algorithm>
#include <array>
#include <bitset>
#include <climits>
#include <cmath>
#include <deque>
#include <forward_list>
#include <functional>
#include <iomanip>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <numeric>
#include <queue>
#include <regex>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <tuple>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <valarray>
#include <vector>

using namespace std;

class Solution {
   public:
    int smallestIndex(vector<int>& nums) {
        int ans = -1;
        for (int i = 0; i < (int)nums.size(); i++) {
            string s = to_string(nums[i]);
            int sum = 0;
            for (auto& e : s) {
                sum += e - '0';
            }
            if (sum == i) {
                ans = i;
                break;
            }
        }
        return ans;
    }
};

// int Solution::smallestIndex(vector<int> nums)

int main() {
    cout << "*** 100668. Smallest Index With Digit Sum Equal to Index ***"
         << endl
         << endl;

    Solution s0;

    {
        cout << "Test 1: ";

        vector<int> nums = {1, 3, 2};
        int ans0 = s0.smallestIndex(nums);
        int exp0 = 2;

        if (ans0 == exp0) {
            cout << "Yes" << endl;
        } else {
            cout << "No" << endl;
            cout << "  Answer: " << ans0 << endl;
            cout << "  Expect: " << exp0 << endl;
        }
    }

    {
        cout << "Test 2: ";

        vector<int> nums = {1, 10, 11};
        int ans1 = s0.smallestIndex(nums);
        int exp1 = 1;

        if (ans1 == exp1) {
            cout << "Yes" << endl;
        } else {
            cout << "No" << endl;
            cout << "  Answer: " << ans1 << endl;
            cout << "  Expect: " << exp1 << endl;
        }
    }

    {
        cout << "Test 3: ";

        vector<int> nums = {1, 2, 3};
        int ans2 = s0.smallestIndex(nums);
        int exp2 = -1;

        if (ans2 == exp2) {
            cout << "Yes" << endl;
        } else {
            cout << "No" << endl;
            cout << "  Answer: " << ans2 << endl;
            cout << "  Expect: " << exp2 << endl;
        }
    }

    return 0;
}
