// Generated by LeetCodeContestHelper at 7/21/2024, 9:51:11 PM
// 3226. Number of Bit Changes to Make Two Integers Equal
// https://leetcode.com/contest/weekly-contest-407/problems/number-of-bit-changes-to-make-two-integers-equal/

#define _USE_MATH_DEFINES
#include <algorithm>
#include <array>
#include <bitset>
#include <climits>
#include <cmath>
#include <deque>
#include <forward_list>
#include <functional>
#include <iomanip>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <numeric>
#include <queue>
#include <regex>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <tuple>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <valarray>
#include <vector>

using namespace std;

class Solution {
   public:
    int minChanges(int n, int k) {
        int ans = 0;
        for (int i = 30; i >= 0; i--) {
            if (!(n & (1 << i)) && (k & (1 << i)))
                return -1;
            else if ((n & (1 << i)) && !(k & (1 << i)))
                ans++;
        }
        return ans;
    }
};

// int Solution::minChanges(int n, int k)

int main() {
    cout << "*** 3226. Number of Bit Changes to Make Two Integers Equal ***"
         << endl
         << endl;

    Solution s0;

    {
        cout << "Test 1: ";

        int n = 13;
        int k = 4;
        int ans0 = s0.minChanges(n, k);
        int exp0 = 2;

        if (ans0 == exp0) {
            cout << "Yes" << endl;
        } else {
            cout << "No" << endl;
            cout << "  Answer: " << ans0 << endl;
            cout << "  Expect: " << exp0 << endl;
        }
    }

    {
        cout << "Test 2: ";

        int n = 21;
        int k = 21;
        int ans1 = s0.minChanges(n, k);
        int exp1 = 0;

        if (ans1 == exp1) {
            cout << "Yes" << endl;
        } else {
            cout << "No" << endl;
            cout << "  Answer: " << ans1 << endl;
            cout << "  Expect: " << exp1 << endl;
        }
    }

    {
        cout << "Test 3: ";

        int n = 14;
        int k = 13;
        int ans2 = s0.minChanges(n, k);
        int exp2 = -1;

        if (ans2 == exp2) {
            cout << "Yes" << endl;
        } else {
            cout << "No" << endl;
            cout << "  Answer: " << ans2 << endl;
            cout << "  Expect: " << exp2 << endl;
        }
    }

    return 0;
}
