// Generated by LeetCodeContestHelper at 7/21/2024, 9:51:40 PM
// 3227. Vowels Game in a String
// https://leetcode.com/contest/weekly-contest-407/problems/vowels-game-in-a-string/

#define _USE_MATH_DEFINES
#include <algorithm>
#include <array>
#include <bitset>
#include <climits>
#include <cmath>
#include <deque>
#include <forward_list>
#include <functional>
#include <iomanip>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <numeric>
#include <queue>
#include <regex>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <tuple>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <valarray>
#include <vector>

using namespace std;

class Solution {
   public:
    bool doesAliceWin(string s) {
        set<char> st = {'u', 'e', 'o', 'a', 'i'};
        int cnt = 0;
        for (auto& e : s) {
            if (st.count(e))
                cnt++;
        }
        return cnt > 0;
    }
};

// bool Solution::doesAliceWin(string s)

int main() {
    cout << "*** 3227. Vowels Game in a String ***" << endl << endl;

    Solution s0;

    {
        cout << "Test 1: ";

        string s = "leetcoder";
        bool ans0 = s0.doesAliceWin(s);
        bool exp0 = true;

        if (ans0 == exp0) {
            cout << "Yes" << endl;
        } else {
            cout << "No" << endl;
            cout << "  Answer: " << ans0 << endl;
            cout << "  Expect: " << exp0 << endl;
        }
    }

    {
        cout << "Test 2: ";

        string s = "bbcd";
        bool ans1 = s0.doesAliceWin(s);
        bool exp1 = false;

        if (ans1 == exp1) {
            cout << "Yes" << endl;
        } else {
            cout << "No" << endl;
            cout << "  Answer: " << ans1 << endl;
            cout << "  Expect: " << exp1 << endl;
        }
    }

    return 0;
}
