// Generated by LeetCodeContestHelper at 5/25/2024, 9:32:56 PM
// 100303. Find Occurrences of an Element in an Array
// https://leetcode.com/contest/biweekly-contest-131/problems/find-occurrences-of-an-element-in-an-array/

#define _USE_MATH_DEFINES
#include <algorithm>
#include <array>
#include <bitset>
#include <climits>
#include <cmath>
#include <deque>
#include <forward_list>
#include <functional>
#include <iomanip>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <numeric>
#include <queue>
#include <regex>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <tuple>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <valarray>
#include <vector>

using namespace std;

class Solution {
   public:
    vector<int> occurrencesOfElement(vector<int>& nums, vector<int>& queries,
                                     int x) {
        vector<int> v;
        for (int i = 0; i < (int)nums.size(); i++) {
            if (nums[i] == x) {
                v.push_back(i);
            }
        }
        vector<int> ans;
        for (auto& e : queries) {
            if (e > (int)v.size()) {
                ans.push_back(-1);
            } else {
                --e;
                ans.push_back(v[e]);
            }
        }
        return ans;
    }
};

// vector<int> Solution::occurrencesOfElement(vector<int> nums, vector<int>
// queries, int x)

int main() {
    cout << "*** 100303. Find Occurrences of an Element in an Array ***" << endl
         << endl;

    Solution s0;

    {
        cout << "Test 1: ";

        vector<int> nums = {1, 3, 1, 7};
        vector<int> queries = {1, 3, 2, 4};
        int x = 1;
        vector<int> ans0 = s0.occurrencesOfElement(nums, queries, x);
        vector<int> exp0 = {0, -1, 2, -1};

        if (ans0 == exp0) {
            cout << "Yes" << endl;
        } else {
            cout << "No" << endl;
            cout << "  Answer: ";
            for (int& i : ans0) {
                cout << i << " ";
            }
            cout << endl << "  Expect: ";
            for (int& i : exp0) {
                cout << i << " ";
            }
            cout << endl;
        }
    }

    {
        cout << "Test 2: ";

        vector<int> nums = {1, 2, 3};
        vector<int> queries = {10};
        int x = 5;
        vector<int> ans1 = s0.occurrencesOfElement(nums, queries, x);
        vector<int> exp1 = {-1};

        if (ans1 == exp1) {
            cout << "Yes" << endl;
        } else {
            cout << "No" << endl;
            cout << "  Answer: ";
            for (int& i : ans1) {
                cout << i << " ";
            }
            cout << endl << "  Expect: ";
            for (int& i : exp1) {
                cout << i << " ";
            }
            cout << endl;
        }
    }

    return 0;
}
