// Generated by LeetCodeContestHelper at 5/1/2024, 4:44:03 PM
// 3028. Ant on the Boundary
// https://leetcode.com/contest/weekly-contest-383/problems/ant-on-the-boundary/

#define _USE_MATH_DEFINES
#include <algorithm>
#include <array>
#include <bitset>
#include <climits>
#include <cmath>
#include <deque>
#include <forward_list>
#include <functional>
#include <iomanip>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <numeric>
#include <queue>
#include <regex>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <tuple>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <valarray>
#include <vector>

using namespace std;

class Solution {
   public:
    int returnToBoundaryCount(vector<int>& nums) {
        int s = 0, ans = 0;
        for (auto& e : nums) {
            s += e;
            if (s == 0)
                ans++;
        }
        return ans;
    }
};

// int Solution::returnToBoundaryCount(vector<int> nums)

int main() {
    cout << "*** 3028. Ant on the Boundary ***" << endl << endl;

    Solution s0;

    {
        cout << "Test 1: ";

        vector<int> nums = {2, 3, -5};
        int ans0 = s0.returnToBoundaryCount(nums);
        int exp0 = 1;

        if (ans0 == exp0) {
            cout << "Yes" << endl;
        } else {
            cout << "No" << endl;
            cout << "  Answer: " << ans0 << endl;
            cout << "  Expect: " << exp0 << endl;
        }
    }

    {
        cout << "Test 2: ";

        vector<int> nums = {3, 2, -3, -4};
        int ans1 = s0.returnToBoundaryCount(nums);
        int exp1 = 0;

        if (ans1 == exp1) {
            cout << "Yes" << endl;
        } else {
            cout << "No" << endl;
            cout << "  Answer: " << ans1 << endl;
            cout << "  Expect: " << exp1 << endl;
        }
    }

    return 0;
}
