// Generated by LeetCodeContestHelper at 5/26/2024, 9:30:38 AM
// 100323. Find the Number of Good Pairs I
// https://leetcode.com/contest/weekly-contest-399/problems/find-the-number-of-good-pairs-i/

#define _USE_MATH_DEFINES
#include <algorithm>
#include <array>
#include <bitset>
#include <climits>
#include <cmath>
#include <deque>
#include <forward_list>
#include <functional>
#include <iomanip>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <numeric>
#include <queue>
#include <regex>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <tuple>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <valarray>
#include <vector>

using namespace std;

class Solution {
   public:
    int numberOfPairs(vector<int>& nums1, vector<int>& nums2, int k) {
        int ans = 0;
        for (auto& e : nums1) {
            for (auto& x : nums2) {
                if (e % (x * k) == 0)
                    ans++;
            }
        }
        return ans;
    }
};

// int Solution::numberOfPairs(vector<int> nums1, vector<int> nums2, int k)

int main() {
    cout << "*** 100323. Find the Number of Good Pairs I ***" << endl << endl;

    Solution s0;

    {
        cout << "Test 1: ";

        vector<int> nums1 = {1, 3, 4};
        vector<int> nums2 = {1, 3, 4};
        int k = 1;
        int ans0 = s0.numberOfPairs(nums1, nums2, k);
        int exp0 = 5;

        if (ans0 == exp0) {
            cout << "Yes" << endl;
        } else {
            cout << "No" << endl;
            cout << "  Answer: " << ans0 << endl;
            cout << "  Expect: " << exp0 << endl;
        }
    }

    {
        cout << "Test 2: ";

        vector<int> nums1 = {1, 2, 4, 12};
        vector<int> nums2 = {2, 4};
        int k = 3;
        int ans1 = s0.numberOfPairs(nums1, nums2, k);
        int exp1 = 2;

        if (ans1 == exp1) {
            cout << "Yes" << endl;
        } else {
            cout << "No" << endl;
            cout << "  Answer: " << ans1 << endl;
            cout << "  Expect: " << exp1 << endl;
        }
    }

    return 0;
}
