// Generated by LeetCodeContestHelper at 5/5/2024, 9:30:57 AM
// 100284. Valid Word
// https://leetcode.com/contest/weekly-contest-396/problems/valid-word/

#define _USE_MATH_DEFINES
#include <algorithm>
#include <array>
#include <bitset>
#include <climits>
#include <cmath>
#include <deque>
#include <forward_list>
#include <functional>
#include <iomanip>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <numeric>
#include <queue>
#include <regex>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <tuple>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <valarray>
#include <vector>

using namespace std;

class Solution {
   public:
    bool ok(char c) {
        return (c >= '0' && c <= '9') || (c >= 'A' && c <= 'Z') ||
               (c >= 'a' && c <= 'z');
    }

    bool isValid(string word) {
        int n = (int)word.size();
        if (n < 3)
            return false;
        int c1 = 0, c2 = 0;
        set<char> st = {'a', 'e', 'i', 'o', 'u'};
        for (auto& c : word) {
            if (!ok(c))
                return false;
            if (st.count(tolower(c)))
                c1++;
            else if ((c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z'))
                c2++;
        }
        return c1 > 0 && c2 > 0;
    }
};

// bool Solution::isValid(string word)

int main() {
    cout << "*** 100284. Valid Word ***" << endl << endl;

    Solution s0;

    {
        cout << "Test 1: ";

        string word = "234Adas";
        bool ans0 = s0.isValid(word);
        bool exp0 = true;

        if (ans0 == exp0) {
            cout << "Yes" << endl;
        } else {
            cout << "No" << endl;
            cout << "  Answer: " << ans0 << endl;
            cout << "  Expect: " << exp0 << endl;
        }
    }

    {
        cout << "Test 2: ";

        string word = "b3";
        bool ans1 = s0.isValid(word);
        bool exp1 = false;

        if (ans1 == exp1) {
            cout << "Yes" << endl;
        } else {
            cout << "No" << endl;
            cout << "  Answer: " << ans1 << endl;
            cout << "  Expect: " << exp1 << endl;
        }
    }

    {
        cout << "Test 3: ";

        string word = "a3$e";
        bool ans2 = s0.isValid(word);
        bool exp2 = false;

        if (ans2 == exp2) {
            cout << "Yes" << endl;
        } else {
            cout << "No" << endl;
            cout << "  Answer: " << ans2 << endl;
            cout << "  Expect: " << exp2 << endl;
        }
    }

    return 0;
}
