// Generated by LeetCodeContestHelper at 6/9/2024, 9:30:59 AM
// 100325. Find the Child Who Has the Ball After K Seconds
// https://leetcode.com/contest/weekly-contest-401/problems/find-the-child-who-has-the-ball-after-k-seconds/

#define _USE_MATH_DEFINES
#include <algorithm>
#include <array>
#include <bitset>
#include <climits>
#include <cmath>
#include <deque>
#include <forward_list>
#include <functional>
#include <iomanip>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <numeric>
#include <queue>
#include <regex>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <tuple>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <valarray>
#include <vector>

using namespace std;

class Solution {
   public:
    int numberOfChild(int n, int k) {
        int ans = 0, dir = -1;
        for (int i = 0; i < k; i++) {
            if (ans == n - 1 || ans == 0)
                dir *= -1;
            ans += dir;
        }
        return ans;
    }
};

// int Solution::numberOfChild(int n, int k)

int main() {
    cout << "*** 100325. Find the Child Who Has the Ball After K Seconds ***"
         << endl
         << endl;

    Solution s0;

    {
        cout << "Test 1: ";

        int n = 3;
        int k = 5;
        int ans0 = s0.numberOfChild(n, k);
        int exp0 = 1;

        if (ans0 == exp0) {
            cout << "Yes" << endl;
        } else {
            cout << "No" << endl;
            cout << "  Answer: " << ans0 << endl;
            cout << "  Expect: " << exp0 << endl;
        }
    }

    {
        cout << "Test 2: ";

        int n = 5;
        int k = 6;
        int ans1 = s0.numberOfChild(n, k);
        int exp1 = 2;

        if (ans1 == exp1) {
            cout << "Yes" << endl;
        } else {
            cout << "No" << endl;
            cout << "  Answer: " << ans1 << endl;
            cout << "  Expect: " << exp1 << endl;
        }
    }

    {
        cout << "Test 3: ";

        int n = 4;
        int k = 2;
        int ans2 = s0.numberOfChild(n, k);
        int exp2 = 2;

        if (ans2 == exp2) {
            cout << "Yes" << endl;
        } else {
            cout << "No" << endl;
            cout << "  Answer: " << ans2 << endl;
            cout << "  Expect: " << exp2 << endl;
        }
    }

    return 0;
}
