// Generated by LeetCodeContestHelper at 6/9/2024, 9:38:37 AM
// 100305. Find the N-th Value After K Seconds
// https://leetcode.com/contest/weekly-contest-401/problems/find-the-n-th-value-after-k-seconds/

#define _USE_MATH_DEFINES
#include <algorithm>
#include <array>
#include <bitset>
#include <climits>
#include <cmath>
#include <deque>
#include <forward_list>
#include <functional>
#include <iomanip>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <numeric>
#include <queue>
#include <regex>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <tuple>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <valarray>
#include <vector>

using namespace std;

class Solution {
   public:
    int valueAfterKSeconds(int n, int k) {
        vector<long long> v(n, 1);
        const long long mod = (long long)1e9 + 7;
        for (int i = 0; i < k; i++) {
            vector<long long> a = {v[0]};
            long long cur = v[0];
            for (int j = 1; j < n; j++) {
                a.push_back((cur + v[j]) % mod);
                cur += v[j];
                cur %= mod;
            }
            v = a;
        }
        return v.back();
    }
};

// int Solution::valueAfterKSeconds(int n, int k)

int main() {
    cout << "*** 100305. Find the N-th Value After K Seconds ***" << endl
         << endl;

    Solution s0;

    {
        cout << "Test 1: ";

        int n = 4;
        int k = 5;
        int ans0 = s0.valueAfterKSeconds(n, k);
        int exp0 = 56;

        if (ans0 == exp0) {
            cout << "Yes" << endl;
        } else {
            cout << "No" << endl;
            cout << "  Answer: " << ans0 << endl;
            cout << "  Expect: " << exp0 << endl;
        }
    }

    {
        cout << "Test 2: ";

        int n = 5;
        int k = 3;
        int ans1 = s0.valueAfterKSeconds(n, k);
        int exp1 = 35;

        if (ans1 == exp1) {
            cout << "Yes" << endl;
        } else {
            cout << "No" << endl;
            cout << "  Answer: " << ans1 << endl;
            cout << "  Expect: " << exp1 << endl;
        }
    }

    return 0;
}
