// Generated by LeetCodeContestHelper at 6/9/2024, 10:09:39 AM
// 100320. Maximum Total Reward Using Operations II
// https://leetcode.com/contest/weekly-contest-401/problems/maximum-total-reward-using-operations-ii/

#define _USE_MATH_DEFINES
#include <algorithm>
#include <array>
#include <bitset>
#include <climits>
#include <cmath>
#include <deque>
#include <forward_list>
#include <functional>
#include <iomanip>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <numeric>
#include <queue>
#include <regex>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <tuple>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <valarray>
#include <vector>

using namespace std;

class Solution {
   public:
    int maxTotalReward(vector<int>& rewardValues) {
        bitset<100000> bs;
        bitset<100000> bs2;
        bs.set(0);
        bs2.set(0);
        int l = 1;
        ranges::sort(rewardValues);
        for (auto& e : rewardValues) {
            while (l < e) {
                if (bs.test(l)) {
                    bs2.set(l);
                }
                l++;
            }
            bs2 <<= e;
            bs |= bs2;
            bs2 >>= e;
        }
        int ans = 0;
        for (int i = 0; i < 100000; i++) {
            if (bs.test(i)) {
                ans = i;
            }
        }
        return ans;
    }
};

// int Solution::maxTotalReward(vector<int> rewardValues)

int main() {
    cout << "*** 100320. Maximum Total Reward Using Operations II ***" << endl
         << endl;

    Solution s0;

    {
        cout << "Test 1: ";

        vector<int> rewardValues = {1, 1, 3, 3};
        int ans0 = s0.maxTotalReward(rewardValues);
        int exp0 = 4;

        if (ans0 == exp0) {
            cout << "Yes" << endl;
        } else {
            cout << "No" << endl;
            cout << "  Answer: " << ans0 << endl;
            cout << "  Expect: " << exp0 << endl;
        }
    }

    {
        cout << "Test 2: ";

        vector<int> rewardValues = {1, 6, 4, 3, 2};
        int ans1 = s0.maxTotalReward(rewardValues);
        int exp1 = 11;

        if (ans1 == exp1) {
            cout << "Yes" << endl;
        } else {
            cout << "No" << endl;
            cout << "  Answer: " << ans1 << endl;
            cout << "  Expect: " << exp1 << endl;
        }
    }

    return 0;
}
