// Generated by LeetCodeContestHelper at 5/1/2024, 7:26:51 AM
// 3012. Minimize Length of Array Using Operations
// https://leetcode.com/contest/biweekly-contest-122/problems/minimize-length-of-array-using-operations/

#define _USE_MATH_DEFINES
#include <algorithm>
#include <array>
#include <bitset>
#include <climits>
#include <cmath>
#include <deque>
#include <forward_list>
#include <functional>
#include <iomanip>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <numeric>
#include <queue>
#include <regex>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <tuple>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <valarray>
#include <vector>

using namespace std;

class Solution {
 public:
  int minimumArrayLength(vector<int>& nums) {
    int m = *min_element(nums.begin(), nums.end());
    int cnt = 0;
    for (auto& e : nums) {
      if (e == m)
        cnt++;
      else if (e % m)
        return 1;
    }
    return (cnt + 1) / 2;
  }
};

// int Solution::minimumArrayLength(vector<int> nums)

int main() {
  cout << "*** 3012. Minimize Length of Array Using Operations ***" << endl
       << endl;

  Solution s0;

  {
    cout << "Test 1: ";

    vector<int> nums = {1, 4, 3, 1};
    int ans0 = s0.minimumArrayLength(nums);
    int exp0 = 1;

    if (ans0 == exp0) {
      cout << "Yes" << endl;
    } else {
      cout << "No" << endl;
      cout << "  Answer: " << ans0 << endl;
      cout << "  Expect: " << exp0 << endl;
    }
  }

  {
    cout << "Test 2: ";

    vector<int> nums = {5, 5, 5, 10, 5};
    int ans1 = s0.minimumArrayLength(nums);
    int exp1 = 2;

    if (ans1 == exp1) {
      cout << "Yes" << endl;
    } else {
      cout << "No" << endl;
      cout << "  Answer: " << ans1 << endl;
      cout << "  Expect: " << exp1 << endl;
    }
  }

  {
    cout << "Test 3: ";

    vector<int> nums = {2, 3, 4};
    int ans2 = s0.minimumArrayLength(nums);
    int exp2 = 1;

    if (ans2 == exp2) {
      cout << "Yes" << endl;
    } else {
      cout << "No" << endl;
      cout << "  Answer: " << ans2 << endl;
      cout << "  Expect: " << exp2 << endl;
    }
  }

  return 0;
}
