// Generated by LeetCodeContestHelper at 4/30/2024, 3:54:20 AM
// 3110. Score of a String
// https://leetcode.com/contest/biweekly-contest-128/problems/score-of-a-string/

#define _USE_MATH_DEFINES
#include <algorithm>
#include <array>
#include <bitset>
#include <climits>
#include <cmath>
#include <deque>
#include <forward_list>
#include <functional>
#include <iomanip>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <numeric>
#include <queue>
#include <regex>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <tuple>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <valarray>
#include <vector>

using namespace std;

class Solution {
   public:
    int scoreOfString(string s) {
        int ans = 0;
        for (int i = 1; i < (int)s.size(); i++) {
            ans += abs(s[i] - s[i - 1]);
        }
        return ans;
    }
};

// int Solution::scoreOfString(string s)

int main() {
    cout << "*** 3110. Score of a String ***" << endl << endl;

    Solution s0;

    {
        cout << "Test 1: ";

        string s = "hello";
        int ans0 = s0.scoreOfString(s);
        int exp0 = 13;

        if (ans0 == exp0) {
            cout << "Yes" << endl;
        } else {
            cout << "No" << endl;
            cout << "  Answer: " << ans0 << endl;
            cout << "  Expect: " << exp0 << endl;
        }
    }

    {
        cout << "Test 2: ";

        string s = "zaz";
        int ans1 = s0.scoreOfString(s);
        int exp1 = 50;

        if (ans1 == exp1) {
            cout << "Yes" << endl;
        } else {
            cout << "No" << endl;
            cout << "  Answer: " << ans1 << endl;
            cout << "  Expect: " << exp1 << endl;
        }
    }

    return 0;
}
