// Generated by LeetCodeContestHelper at 6/22/2024, 9:35:31 PM
// 100344. Minimum Operations to Make Binary Array Elements Equal to One I
// https://leetcode.com/contest/biweekly-contest-133/problems/minimum-operations-to-make-binary-array-elements-equal-to-one-i/

#define _USE_MATH_DEFINES
#include <algorithm>
#include <array>
#include <bitset>
#include <climits>
#include <cmath>
#include <deque>
#include <forward_list>
#include <functional>
#include <iomanip>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <numeric>
#include <queue>
#include <regex>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <tuple>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <valarray>
#include <vector>

using namespace std;

class Solution {
   public:
    int minOperations(vector<int>& nums) {
        int ans = 0;
        for (int i = 0; i <= (int)nums.size() - 3; i++) {
            if (!nums[i]) {
                ans++;
                for (int j = 0; j < 3; j++) {
                    nums[i + j] = 1 - nums[i + j];
                }
            }
        }
        return count(nums.begin(), nums.end(), 0) ? -1 : ans;
    }
};

// int Solution::minOperations(vector<int> nums)

int main() {
    cout << "*** 100344. Minimum Operations to Make Binary Array Elements "
            "Equal to One I ***"
         << endl
         << endl;

    Solution s0;

    {
        cout << "Test 1: ";

        vector<int> nums = {0, 1, 1, 1, 0, 0};
        int ans0 = s0.minOperations(nums);
        int exp0 = 3;

        if (ans0 == exp0) {
            cout << "Yes" << endl;
        } else {
            cout << "No" << endl;
            cout << "  Answer: " << ans0 << endl;
            cout << "  Expect: " << exp0 << endl;
        }
    }

    {
        cout << "Test 2: ";

        vector<int> nums = {0, 1, 1, 1};
        int ans1 = s0.minOperations(nums);
        int exp1 = -1;

        if (ans1 == exp1) {
            cout << "Yes" << endl;
        } else {
            cout << "No" << endl;
            cout << "  Answer: " << ans1 << endl;
            cout << "  Expect: " << exp1 << endl;
        }
    }

    return 0;
}
