// Generated by LeetCodeContestHelper at 5/1/2024, 8:52:57 AM
// 2929. Distribute Candies Among Children II
// https://leetcode.com/contest/biweekly-contest-117/problems/distribute-candies-among-children-ii/

#define _USE_MATH_DEFINES
#include <algorithm>
#include <array>
#include <bitset>
#include <climits>
#include <cmath>
#include <deque>
#include <forward_list>
#include <functional>
#include <iomanip>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <numeric>
#include <queue>
#include <regex>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <tuple>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <valarray>
#include <vector>

using namespace std;

class Solution {
   public:
    long long distributeCandies(int n, int limit) {
        vector<vector<long long>> dp(4, vector<long long>(n + 1));
        vector<vector<long long>> pref(4, vector<long long>(n + 1));
        dp[0][0] = 1;
        for (int i = 0; i <= n; i++) {
            pref[0][i] = 1;
        }
        for (int i = 1; i <= 3; i++) {
            for (int j = 0; j <= min(n, i * limit); j++) {
                dp[i][j] += pref[i - 1][j];
                if (j - limit > 0) {
                    dp[i][j] -= pref[i - 1][j - limit - 1];
                }
            }
            pref[i][0] = dp[i][0];
            for (int j = 1; j <= n; j++) {
                pref[i][j] = pref[i][j - 1] + dp[i][j];
            }
        }
        return dp[3][n];
    }
};

// long long Solution::distributeCandies(int n, int limit)

int main() {
    cout << "*** 2929. Distribute Candies Among Children II ***" << endl
         << endl;

    Solution s0;

    {
        cout << "Test 1: ";

        int n = 5;
        int limit = 2;
        long long ans0 = s0.distributeCandies(n, limit);
        long long exp0 = 3;

        if (ans0 == exp0) {
            cout << "Yes" << endl;
        } else {
            cout << "No" << endl;
            cout << "  Answer: " << ans0 << endl;
            cout << "  Expect: " << exp0 << endl;
        }
    }

    {
        cout << "Test 2: ";

        int n = 3;
        int limit = 3;
        long long ans1 = s0.distributeCandies(n, limit);
        long long exp1 = 10;

        if (ans1 == exp1) {
            cout << "Yes" << endl;
        } else {
            cout << "No" << endl;
            cout << "  Answer: " << ans1 << endl;
            cout << "  Expect: " << exp1 << endl;
        }
    }

    return 0;
}
