// Generated by LeetCodeContestHelper at 5/19/2024, 11:38:36 AM
// 3151. Special Array I
// https://leetcode.com/contest/weekly-contest-398/problems/special-array-i/

#define _USE_MATH_DEFINES
#include <algorithm>
#include <array>
#include <bitset>
#include <climits>
#include <cmath>
#include <deque>
#include <forward_list>
#include <functional>
#include <iomanip>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <numeric>
#include <queue>
#include <regex>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <tuple>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <valarray>
#include <vector>

using namespace std;

class Solution {
   public:
    bool isArraySpecial(vector<int>& nums) {
        for (int i = 0; i < (int)nums.size() - 1; i++) {
            if (nums[i] % 2 && nums[i + 1] % 2)
                return false;
            if (nums[i] % 2 == 0 && nums[i + 1] % 2 == 0)
                return false;
        }
        return true;
    }
};

// bool Solution::isArraySpecial(vector<int> nums)

int main() {
    cout << "*** 3151. Special Array I ***" << endl << endl;

    Solution s0;

    {
        cout << "Test 1: ";

        vector<int> nums = {1};
        bool ans0 = s0.isArraySpecial(nums);
        bool exp0 = true;

        if (ans0 == exp0) {
            cout << "Yes" << endl;
        } else {
            cout << "No" << endl;
            cout << "  Answer: " << ans0 << endl;
            cout << "  Expect: " << exp0 << endl;
        }
    }

    {
        cout << "Test 2: ";

        vector<int> nums = {2, 1, 4};
        bool ans1 = s0.isArraySpecial(nums);
        bool exp1 = true;

        if (ans1 == exp1) {
            cout << "Yes" << endl;
        } else {
            cout << "No" << endl;
            cout << "  Answer: " << ans1 << endl;
            cout << "  Expect: " << exp1 << endl;
        }
    }

    {
        cout << "Test 3: ";

        vector<int> nums = {4, 3, 1, 6};
        bool ans2 = s0.isArraySpecial(nums);
        bool exp2 = false;

        if (ans2 == exp2) {
            cout << "Yes" << endl;
        } else {
            cout << "No" << endl;
            cout << "  Answer: " << ans2 << endl;
            cout << "  Expect: " << exp2 << endl;
        }
    }

    return 0;
}
