// Generated by LeetCodeContestHelper at 5/19/2024, 11:39:24 AM
// 3153. Sum of Digit Differences of All Pairs
// https://leetcode.com/contest/weekly-contest-398/problems/sum-of-digit-differences-of-all-pairs/

#define _USE_MATH_DEFINES
#include <algorithm>
#include <array>
#include <bitset>
#include <climits>
#include <cmath>
#include <deque>
#include <forward_list>
#include <functional>
#include <iomanip>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <numeric>
#include <queue>
#include <regex>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <tuple>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <valarray>
#include <vector>

using namespace std;

class Solution {
   public:
    long long sumDigitDifferences(vector<int>& nums) {
        int sz = to_string(nums.front()).size();
        vector<vector<int>> cnt(sz, vector<int>(10));
        long long ans = 0;
        for (auto& e : nums) {
            string s = to_string(e);
            long long sum = 0;
            for (int i = 0; i < sz; i++) {
                int c = s[i] - '0';
                for (int j = 0; j < 10; j++) {
                    if (j != c) {
                        sum += cnt[i][j];
                    }
                }
                cnt[i][c]++;
            }
            ans += sum;
        }
        return ans;
    }
};

// long long Solution::sumDigitDifferences(vector<int> nums)

int main() {
    cout << "*** 3153. Sum of Digit Differences of All Pairs ***" << endl
         << endl;

    Solution s0;

    {
        cout << "Test 1: ";

        vector<int> nums = {13, 23, 12};
        long long ans0 = s0.sumDigitDifferences(nums);
        long long exp0 = 4;

        if (ans0 == exp0) {
            cout << "Yes" << endl;
        } else {
            cout << "No" << endl;
            cout << "  Answer: " << ans0 << endl;
            cout << "  Expect: " << exp0 << endl;
        }
    }

    {
        cout << "Test 2: ";

        vector<int> nums = {10, 10, 10, 10};
        long long ans1 = s0.sumDigitDifferences(nums);
        long long exp1 = 0;

        if (ans1 == exp1) {
            cout << "Yes" << endl;
        } else {
            cout << "No" << endl;
            cout << "  Answer: " << ans1 << endl;
            cout << "  Expect: " << exp1 << endl;
        }
    }

    return 0;
}
