// Generated by LeetCodeContestHelper at 5/12/2024, 9:49:56 AM
// 100296. Permutation Difference between Two Strings
// https://leetcode.com/contest/weekly-contest-397/problems/permutation-difference-between-two-strings/

#define _USE_MATH_DEFINES
#include <algorithm>
#include <array>
#include <bitset>
#include <climits>
#include <cmath>
#include <deque>
#include <forward_list>
#include <functional>
#include <iomanip>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <numeric>
#include <queue>
#include <regex>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <tuple>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <valarray>
#include <vector>

using namespace std;

class Solution {
   public:
    int findPermutationDifference(string s, string t) {
        vector<int> v1(26);
        vector<int> v2(26);
        int n = (int)s.size();
        for (int i = 0; i < n; i++) {
            v1[s[i] - 'a'] = i;
            v2[t[i] - 'a'] = i;
        }
        int ans = 0;
        for (int i = 0; i < 26; i++) {
            ans += abs(v1[i] - v2[i]);
        }
        return ans;
    }
};

// int Solution::findPermutationDifference(string s, string t)

int main() {
    cout << "*** 100296. Permutation Difference between Two Strings ***" << endl
         << endl;

    Solution s0;

    {
        cout << "Test 1: ";

        string s = "abc";
        string t = "bac";
        int ans0 = s0.findPermutationDifference(s, t);
        int exp0 = 2;

        if (ans0 == exp0) {
            cout << "Yes" << endl;
        } else {
            cout << "No" << endl;
            cout << "  Answer: " << ans0 << endl;
            cout << "  Expect: " << exp0 << endl;
        }
    }

    {
        cout << "Test 2: ";

        string s = "abcde";
        string t = "edbac";
        int ans1 = s0.findPermutationDifference(s, t);
        int exp1 = 12;

        if (ans1 == exp1) {
            cout << "Yes" << endl;
        } else {
            cout << "No" << endl;
            cout << "  Answer: " << ans1 << endl;
            cout << "  Expect: " << exp1 << endl;
        }
    }

    return 0;
}
