// Generated by LeetCodeContestHelper at 5/22/2024, 8:41:47 PM
// 3005. Count Elements With Maximum Frequency
// https://leetcode.com/contest/weekly-contest-380/problems/count-elements-with-maximum-frequency/

#define _USE_MATH_DEFINES
#include <algorithm>
#include <array>
#include <bitset>
#include <climits>
#include <cmath>
#include <deque>
#include <forward_list>
#include <functional>
#include <iomanip>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <numeric>
#include <queue>
#include <regex>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <tuple>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <valarray>
#include <vector>

using namespace std;

class Solution {
   public:
    int maxFrequencyElements(vector<int>& nums) {
        vector<int> cnt(101);
        for (auto& e : nums) {
            cnt[e]++;
        }
        int mx = *ranges::max_element(cnt);
        int ans = 0;
        for (auto& e : cnt) {
            if (e == mx) {
                ans += mx;
            }
        }
        return ans;
    }
};

// int Solution::maxFrequencyElements(vector<int> nums)

int main() {
    cout << "*** 3005. Count Elements With Maximum Frequency ***" << endl
         << endl;

    Solution s0;

    {
        cout << "Test 1: ";

        vector<int> nums = {1, 2, 2, 3, 1, 4};
        int ans0 = s0.maxFrequencyElements(nums);
        int exp0 = 4;

        if (ans0 == exp0) {
            cout << "Yes" << endl;
        } else {
            cout << "No" << endl;
            cout << "  Answer: " << ans0 << endl;
            cout << "  Expect: " << exp0 << endl;
        }
    }

    {
        cout << "Test 2: ";

        vector<int> nums = {1, 2, 3, 4, 5};
        int ans1 = s0.maxFrequencyElements(nums);
        int exp1 = 5;

        if (ans1 == exp1) {
            cout << "Yes" << endl;
        } else {
            cout << "No" << endl;
            cout << "  Answer: " << ans1 << endl;
            cout << "  Expect: " << exp1 << endl;
        }
    }

    return 0;
}
